### ISSUE TITLE
Support embedded mail server

### ISSUE THREAD

**Issue by dacrome** [osiam/addon-self-administration#119]
To start the self-administration out-of-the-box, it would be really nice if no mail server is configured an embedded mail server will be started to provide a fully functional application (except the fact that the self-admin needs running auth- and resource-server). This is more intended for an easy try of the self-admin without the disadvantage of setting up a mail server. I like the idea of starting a greenmail smtp server when nothing is configured. This idea fits even more if we migrate to Spring Boot and run the self-admin with a simple java -jar.
I think the [port](https://github.com/osiam/addon-self-administration/blob/master/src/main/java/org/osiam/addons/self_administration/Config.java#L90) should be by default an empty string and if the port is not configured the mail configuration should be changed to the greenmail parameters. right?

**Comment by tkrille** [comment]
+1

> I think the [port](https://github.com/osiam/addon-administration/blob/master/src/main/java/org/osiam/addons/administration/mail/MailConfig.java#L19) should be an empty string by default and if the port is not configured the mail configuration should be changed to the greenmail parameters. right?

Yes, if nothing is configured regarding the mail server we start a fake one and configure the app accordingly.

**Comment by tkrille** [comment]
Obsoleted by osiam/osiam#158

**Comment by tkrille** [comment]
Addon Self Administration is obsolete.
