### ISSUE TITLE
Spring Boot: Which default port should we use?

### ISSUE THREAD

**Issue by dacrome** [osiam/addon-self-administration#120]
If we migrate to Spring Boot, we need to set a default ports for the service and the admin/metrics endpoints. Any suggestions? Remember that we need to set two ports for every OSIAM component (auth-server, resource-server, self-administration, addon-administration). Maybe something like:
Service: 41001
Admin: 42001

**Comment by tkrille** [comment]
The Debian packages install OSIAM configured with port 6001. ~~Maybe we choose something in that range?~~ But this seems to be reserved for x11. So we have to find some other, "unused" port range. What about 50511 - 50514 and 50510 for a single port deployment?

IMO we should not expose a distinct admin port but rather protect admin resources with OAuth.

**Comment by tkrille** [comment]
This discussion moved to osiam/osiam#6.
