### ISSUE TITLE
Run the self-administration as a standalone application

### ISSUE THREAD

**Issue by dacrome** [osiam/addon-self-administration#121]
Like [already discussed](https://github.com/osiam/osiam/issues/5) in the OSIAM umbrella repo, the time is right to support standalone application with Spring Boot fat jars. But there are several steps to discuss for an easy migration and what of the Spring Boot magic we should use to make the life easier for operations and developers. I will create a few issues to discuss these steps. This issue was only created to clarify the need for the migration to Spring Boot. This issue will be closed if the migration is finally done!

**Comment by tkrille** [comment]
I formalized this in #133 and made this issue somewhat obsolete. Sorry 'bout that.
