### ISSUE TITLE
Spring Boot: External configuration

### ISSUE THREAD

**Issue by dacrome** [osiam/addon-self-administration#122]
If we migrate to Spring Boot, configuration and web-resource (template, css, js and message) files should be customizable like before.

If you like to override the internal provided default [properties](https://github.com/osiam/addon-self-administration/blob/master/src/main/deploy/addon-self-administration.properties), the easiest way is to provide a copy of this file as application.properties in the same folder where the jar is started. This is a feature of Spring Boot, which loads properties from [several locations](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files). Another way is to start the fat jar with `java -jar self-admin.jar --spring.config.location=/my/location`. There are many options to load the configuration file.

I think we should provide the same way for the web-resources, but a little bit fancier. Thanks to the idea of @tkrille, we should copy the web-resources out of the jar in the same folder where the jar lives (or any other default folder) to make it easy as possible to customize these files. This will be prevent if the web-resource property is set when starting the jar (e.g. `java -jar self-admin.jar --osiam.self.admin.resource.location=/var/lib/osiam/self-admin`). For sure the external resource location is also configurable with the external properties.

Any objections?

**Comment by tkrille** [comment]
I do like it. We should consider some edge cases and add some safety nets, so that we don't clutter the current folder of the user.

**Comment by dacrome** [comment]
Yes, but how should the external configuration copy proceed?
Copy properties and web-resource files in current folder / default folder (like /var/lib/osiam/self-administration) and use them directly. Do not using the internal configuration and not putting them in the classpath, maybe the src/main/deploy folder is where they should stay to copy them to the external folder? But then the jar isn't runnable without the external copy step...

**Comment by tkrille** [comment]
Isn't it possible to first look at the (possibly) configured external location and if nithing was found to load the resources from the classpath or some other directory in the jar? If the external path is not configured, we can still extract to `/tmp` or just use the internal stuff. We could also make the copying configurable (`o.o.self-admin.initExternalResources`). With no external location and no `initExternalResources` set, we'd just use the internal stuff or extract to `/tmp/{some random stuff}` and use this folder for resources.

**Comment by dacrome** [comment]
> Isn't it possible to first look at the (possibly) configured external location and if nothing was found to load the resources from the classpath or some other directory in the jar?

Yes it is, see current status of #127. The resources will be used in [`src/main/resources`](https://github.com/dacrome/addon-self-administration/tree/switch-to-spring-boot/src/main/resources) (=web-resources + properties file) if no external location is configured or the resource file is not existing in the external location.

> If the external path is not configured, we can still extract to /tmp or just use the internal stuff.

Ok, that could be the process when starting the app:

1. Check if external location is configured
2. If not, copy everything from [`src/main/resources`](https://github.com/dacrome/addon-self-administration/tree/switch-to-spring-boot/src/main/resources) to `/tmp` (or another default location)

If the installer deletes everything in `/tmp` except one changed template file, at runtime there will be always the internal resources available. But how to check the external location? If `/tmp/addon-self-administration` is existing?

**Comment by tkrille** [comment]
> 2. If not, copy everything from `src/main/resources` to /tmp (or another default location)

That's not possible. At runtime there is no `src/main/resources` folder anymore, but just the complete classpath. Seems kind of tricky to just extract the files needed. OTOH there's no need to extract the `application.properties` or `application.yaml`, because it must be there for Spring Boot to start.

**Comment by tkrille** [comment]
> If the installer deletes everything in /tmp except one changed template file, at runtime there will be always the internal resources available. But how to check the external location? If /tmp/addon-self-administration is existing?

Maybe it's enough to just extract the assets, if some thing like `osiam.home` or `OSIAM_HOME` is set. Otherwise the internal stuff from the classpath will be used.

**Comment by tkrille** [comment]
This must be addressed and solved globally for all projects. See the discussion here: https://github.com/osiam/osiam/issues/36
