### ISSUE TITLE
Spring Boot: Next step war deployment

### ISSUE THREAD

**Issue by dacrome** [osiam/addon-self-administration#124]
As I already mentioned, to provide the self-admin as a fully functional standalone application in form of a fat jar, some migration steps need to be done. Next step should be the migration of the maven pom to Spring Boot. The deployer doesn't have to change anything, the self-administration will be run as a war like before in an application container (and with the same configuration mess). Anyway it's a fat war which is theoretically runnable with java -jar addon-self-administration.war. But the fact that we didn't provide the properties [configuration files and the web-resources](https://github.com/osiam/addon-self-administration/tree/master/src/main/deploy) within the classpath, the self-administration isn't runnable as fat war, because of the missing files.
There are two ways (I guess) to get rid off this problem:
* Throw an exception in the main method to prevent the run via java -jar
* Link the config files as an external classpath if possible

But I'm not sure if we should put so much work to get this running, because next step is the switch to a fat jar without tomcat deployment... what do you think?

**Comment by dacrome** [comment]
I ended up by handling the problem with fat war and the missing config files in the classpath [with throwing an exception](https://github.com/osiam/addon-self-administration/pull/125/files#diff-b5fc47c897d1948c521445388e13ab1fR29).

**Comment by tkrille** [comment]
if you don't run it with `java -jar ...` you can actually set up any classpath you like.

**Comment by tkrille** [comment]
and why not put the config and other resources into the classpath of the war? e could add the contents of `src/main/deploy` as resource folder with Maven.

**Comment by dacrome** [comment]
But how? java -cp "/var/lib/addon-self-administration" addon-self-administration.war ?

**Comment by tkrille** [comment]
`java -cp "/usr/lib/osiam/self-admin.jar;/var/lib/osiam/self-admin;/etc/osiam/self-admin" org.osiam.self_admin.SelfAdmin [some arguments]` or something like that
