### ISSUE TITLE
Error message with enabled user notifications for account deletion

### ISSUE THREAD

**Issue by tpick** [osiam/addon-self-administration#130]
When the "notify user" checkbox is enabled for Account deactivation, the following error message is shown. The user does not receive an e-mail, but the deactivation has occurred nonetheless.

Exception: Error resolving template "deactivate-email", template might not exist or might not be accessible by any of the configured Template Resolvers
org.thymeleaf.exceptions.TemplateInputException: Error resolving template "deactivate-email", template might not exist or might not be accessible by any of the configured Template Resolvers
at org.thymeleaf.TemplateRepository.getTemplate(TemplateRepository.java:246)
at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1104)
at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060)

It seems that the template is expected to have another name.

/etc/osiam/addon-self-administration/templates/mail/deactivation-email.html ->
/etc/osiam/addon-self-administration/templates/mail/deactivate-email.html

**Comment by dacrome** [comment]
This is the wrong repo, please create a new issue in https://github.com/osiam/addon-administration
