### ISSUE TITLE
Registration: compensation for failed email delivery

### ISSUE THREAD

**Issue by tkrille** [osiam/addon-self-administration#131]
A failed email delivery will not remove the newly created user. That's a problem, because if the user tries to register again, their username will already be taken. There should be a way to compensate this, e.g. delete the user if the mail delivery failed and request the user to try again. I think, that a similar compensation for lost password and change email is **not** necessary.

**Comment by wallner** [comment]
This is a duplicate of #85 and was fixed by @sputnik27 in #138. So, if nobody has any objections I'm going to label it as duplicate and close it.

**Comment by tkrille** [comment]
Yes, good catch. Thanks!
