### ISSUE TITLE
Current master is not compatible with OSIAM 2.x

### ISSUE THREAD

**Issue by tkrille** [osiam/addon-self-administration#180]
The Self-Admin uses `OsiamConnector.getMe()` that is only compatible with OSIAM 3.0. What should we do about this? We could make it compatible again, because the Self-Admin is able to detect, whether it is configured for OSIAM 2.x or 3.x. Or we leave it incompatible, releasing version 2.0 and ~~annoying~~ forcing the current users to update to OSIAM 3.0. What do you think?

**Comment by tkrille** [comment]
We could also make `OsiamConnector.getMe()` aware of the version of OSIAM that it connects to. Should be no big deal.

**Comment by dacrome** [comment]
We should release version 2.0 and leave it incompatible.

**Comment by tkrille** [comment]
Why do you think so? I'd vote for making the connector aware of the OSIAM version it connects to. This is because, I want to give our users some time to update to OSIAM 3.0 but still get the latest fixes and changes in the Add-Ons.

**Comment by dacrome** [comment]
Okay, if it is no big deal... Do you create an issue in the connector repo to make `OsiamConnector.getMe()` compatible with OSIAM 2.x and 3.x?

**Comment by tkrille** [comment]
Yes

**Comment by tkrille** [comment]
https://github.com/osiam/connector4java/issues/217
