### ISSUE TITLE
Switch from xml to java configuration

### ISSUE THREAD

**Issue by dacrome** [osiam/addon-self-administration#72]
The xml configuration should be removed and migrated to java configuration. The Spring Framework provides this since version 3.1 and this can be done as a first step to [Spring Boot](http://projects.spring.io/spring-boot/). For reference, these steps can be used to apply also to the [OSIAM server](https://github.com/osiam/server).

**Comment by dacrome** [comment]
This will be done when switching to Spring Boot like [discussed](https://github.com/osiam/osiam/issues/5) in the osiam umbrella repo

**Comment by dacrome** [comment]
After we discussed again the migration to Spring Boot, @tkrille and I decided that it would be better to do the migration in small steps. The first step should be the switch from xml to java configuration. Next steps will be created as issues to enable us to discuss them individually.

**Comment by tkrille** [comment]
when will the PR arrive? :)
