### ISSUE TITLE
User creation not rolled back after sending the activation mail failed

### ISSUE THREAD

**Issue by tpick** [osiam/addon-self-administration#85]
When the server fails to send the activation mail, the user creation is not rolled back. When trying to register the same user after a failed attempt, the user name is already taken. The user creation has to be rolled back after an error occurs.

**Comment by dacrome** [comment]
Verified. This can be fixed together with issue https://github.com/osiam/addon-self-administration/issues/82

**Comment by tkrille** [comment]
This issue should be fixed on it's own. Seems that #125 fixes #82 but not this one.

**Comment by dacrome** [comment]
Yes.
