### ISSUE TITLE
Null handling in PostalCode

### ISSUE THREAD

**Issue by smancke** [osiam/addon-self-administration#91]
If no postalCode is given in the registration, OSIAM saves a string value "null" for the postal code.
The address update over the java api leads to a similar behavior: On saving null, the string "null" gets saved.

A fix for this is important for us.

**Comment by dacrome** [comment]
verified

**Comment by dacrome** [comment]
I wrote verified, but I only checked the code... in the postgres there isn't any string, the fields are empty. So you [configured the self-admin](https://github.com/osiam/addon-self-administration/blob/master/src/main/deploy/addon-self-administration.properties#L51) to show the input field for 'postalCode' but leave the input field blank?

**Comment by dacrome** [comment]
Verified. An empty address added to the user also if non of the address fields are set.

**Comment by tkrille** [comment]
this also correlates with osiam/resource-server#8
